// Generated by https://quicktype.io

export interface GetAnimalResponse {
  _id: string;
  dniDueno: string;
  idPelaje: string;
  idCaravana: string;
  sexo: string;
  edad: string;
  __v: number;
}
